#!/usr/bin/sh
# Wrapper script for Plexamp.

# The plexamp binary has a RUNPATH of its origin folder.
# So remove the RUNPATH from the binary, put all the libraries in its private
# folder and make sure that only the authy binary can access them.

export LD_LIBRARY_PATH="INSTALL_DIR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

declare -a FLAGS=(--enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist --enable-features=UseSkiaRenderer)

if [[ $XDG_SESSION_TYPE == "wayland" ]]; then
    WAYLAND_SOCKET=${WAYLAND_DISPLAY:-"wayland-0"}

    if [[ -e "$XDG_RUNTIME_DIR/${WAYLAND_SOCKET}" ]]; thne
        echo "Wayland socket is available, running natively on Wayland."
        FLAGS+=(--ozone-platform=wayland)
    else
        echo "Wayland socket not available, running through Xwayland."
    fi
fi

echo "Passing the following arguments to Electron:"
printf "  %s\n" "${FLAGS[@]}"

exec INSTALL_DIR/plexamp "${FLAGS[@]}" "$@"
